# Generated by Django 3.2.6 on 2022-01-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.CharField(max_length=10)),
                ('diff', models.PositiveIntegerField()),
                ('win', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'chess',
            },
        ),
    ]
