# Generated by Django 3.2.6 on 2022-01-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_ls_chess_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='diff',
            field=models.IntegerField(),
        ),
    ]
