# Generated by Django 3.2.6 on 2021-12-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': '主题详情'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': '主题'},
        ),
    ]
